Fixy

diff --git a/config/registry-kind/configmap.yaml b/config/registry-kind/configmap.yaml
--- a/config/registry-kind/configmap.yaml
+++ b/config/registry-kind/configmap.yaml
@@ -1,9 +1,9 @@
 apiVersion: v1
 kind: ConfigMap
 metadata:
-  name: allow-bundled-registry-script
+  name: configure-cri
 data:
-  allow-bundled-registry.sh: |
+  configure-cri.sh: |
     #!/usr/bin/env bash
 
     set -x
@@ -29,4 +29,6 @@ data:
     EOF
         fi
         nsenter --target 1 --mount bash -c "systemctl is-active --quiet containerd && echo 'Restarting containerd' && systemctl restart containerd"
+        # Wait for containerd to be ready so that skaffold doesn't fail.
+        nsenter --target 1 --mount bash -c "while ! ctr -n k8s.io containers ls; do sleep 1; done"
     fi
